C RANDOMLY DISTRIBUTE PARTICLES IN ELLIPTICAL COORDINATES
C NEED G05DAF FROM NAG
C COLLECT OUTPUT TO FILE AND VIM with %s/^/1^M'#183'^MS^M;1,2m$
C FOR INPUT TO ANNOT
	DOUBLE PRECISION QXRAN,QYRAN,G05DAF
	DOUBLE PRECISION QTRAN,QRRAN,QCOSX,QSINX
	DOUBLE PRECISION X0,Y0,RHOMIN,RHOMAX
C CENTRE OF ELLIPSE
        X0=1.5D0
        Y0=0.5D0
C RANGE IN MINOR AXIS A
        RHOMIN=0.6D0
        RHOMAX=1.2D0
        RHOMAX=0.8D0
        RHOMAX=0.9D0
C MAJOR AXIS B
        RHOB=2.D0
C NUMBER OF POINTS O/P
        NIMAX=100
        NIMAX=150
C	DO 20 J=1,30
C	QXRAN=G05DAF(0.D0,1.D0)
C	QYRAN=G05DAF(0.D0,1.D0)
C	ZXRAN=QXRAN
C	ZYRAN=QYRAN
C	WRITE(6,*) ZXRAN,ZYRAN
C  20    CONTINUE
        I=0
	DO 30 J=1,1000
	QRRAN=G05DAF(RHOMIN,RHOMAX)
	QTRAN=G05DAF(-1.D0,1.D0)
	QCOSX=COS(QTRAN)
	QSINX=SIN(QTRAN)
        ELLFAC=1.D0/SQRT( (QCOSX/QRRAN)**2+ (QSINX/RHOB)**2 )
	ZXRAN=X0-QCOSX*ELLFAC
	ZYRAN=Y0+QSINX*ELLFAC
        IF ( ZYRAN > 0.0 .AND. ZYRAN < 0.98 ) THEN
	WRITE(6,*) ZXRAN,ZYRAN
        I=I+1
        IF (I>NIMAX) GO TO 999
        END IF
  30    CONTINUE
 999    CONTINUE
	STOP
	END
