C RANDOMLY DISTRIBUTE PARTICLES IN RECTANGULAR COORDINATES
C NEED G05DAF FROM NAG
C COLLECT OUTPUT TO FILE AND VIM with %s/^/1^M'#183'^MS^M;1,2m$
C FOR INPUT TO ANNOT
	DOUBLE PRECISION QXRAN,QYRAN,G05DAF
	DOUBLE PRECISION X0,Y0,X1,Y1
	DOUBLE PRECISION YMED,YSHIFT
        YSHIFT=0.05D0
C.BLUE        YSHIFT=0.1D0    !blue
C BOTTOM LEFT CORNER (TO GREEN)
        X0=0.52D0
        Y0=0.19D0
C (TO BLUE)
C.BLUE        X0=0.76D0    !blue
C.BLUE        Y0=0.10D0    !blue
C TOP RIGHT CORNER
        X1=0.72D0
        Y1=0.30D0
C (TO BLUE)
C.BLUE        X1=0.96D0    !blue
C.BLUE        Y1=0.30D0    !blue
C SPLIT AT THIS VALUE
        YMED=0.25D0
C.BLUE        YMED=(Y0+Y1)/2    !blue
C NUMBER OF POINTS O/P
        NIMAX=50
        I=0
 	DO 30 J=1,3*NIMAX
 	QXRAN=G05DAF(X0,X1)
 	QYRAN=G05DAF(Y0,Y1)
 	ZXRAN=QXRAN
 	ZYRAN=QYRAN
        IF ( ZXRAN > 1.02*X0 .AND. ZXRAN < 0.98*X1 ) THEN
        IF ( ZYRAN > 1.02*Y0 .AND. ZYRAN < 0.98*Y1 ) THEN
        IF ( ZYRAN > YMED ) THEN
	WRITE(6,*) ZXRAN,ZYRAN+YSHIFT
        ELSE
	WRITE(6,*) ZXRAN,ZYRAN
        END IF
        I=I+1
        IF (I>NIMAX) GO TO 999
        END IF
        END IF
  30    CONTINUE
 999    CONTINUE
	STOP
	END
